---
- name: Set up debian box
  hosts: all
  pre_tasks:
    - name: Set ansible_become_exe for sudo-rs (Ubuntu) boxes
      ansible.builtin.set_fact:
        ansible_become_exe: /usr/bin/sudo.ws
      when:
        - ansible_facts['distribution'] == 'Ubuntu'
        - ansible_facts['distribution_version'] is version('25.10', '>=')
      tags: always
  roles:
    - system
    - role: disks
    # A little redundant, but I typo this enough to have both
      when:
        - "'vm' not in group_names"
        - "'vms' not in group_names"
        - "'pi' not in group_names"
        - "'pis' not in group_names"
    - editor
    #   - mounts
    - backups
    #   - containers
    - terminal
    - role: artis3n.tailscale.machine
      when: "'tailscale' in group_names"
      tags: tailscale
    - notifications
    - file_manager
    #   - reverse_proxy
    - drift_management
